INFO("POWER", "PWR", 1, power)
INFO("AUDIO ATT", "ATT", 3, audio_att)
INFO("AUDIO MUTE", "AMT", 1, audio_mute)
INFO("VIDEO MUTE", "VMT", 1, video_mute)
INFO("VOLUME", "VOL", 1, volume)
INFO("TONE BASS", "TOB", 1, tone_bass)
INFO("TONE TREBLE", "TOT", 1, tone_treble)
INFO_KNOW("SOURCE Select", "SRC", 1, ST_KNOW_video_source | ST_KNOW_audio_source, source_select)
INFO("Multi Channel (7.1 Channel Input)", "71C", 1, multi_channel_input)
INFO("MDMI AUDIO MODE", "HAM", 1, hdmi_audio_through)
INFO("Source Input State", "IST", 1, source_input_state)
INFO("SLEEP", "SLP", 2, sleep)
INFO("MENU", "MNU", 4, menu)
INFO_ACK_ONLY("CURSOR", "CUR")
INFO_KNOW_NO_AUTO("DC TRG.", "DCT", 0, dc_trigger)
INFO("FRONT KEY LOCK", "FKL", 1, front_key_lock)
INFO("Simple Setup", "SSU", 4, simple_setup)
INFO("Surr. Mode", "SUR", 2, surround_mode)
INFO("Dolby Headphone Mode", "DHM", 3, dolby_headphone_mode)
INFO_KNOW("Test Tone", "TTO", 1, ST_KNOW_test_tone_enabled | ST_KNOW_test_tone_auto | ST_KNOW_test_tone_channel, test_tone)
INFO("Night Mode", "NGT", 3, night_mode)
INFO("Signal Format", "SIG", 4, digital_signal_format)
INFO_NO_AUTO("Sampling Frequency", "SFQ", sampling_frequency)
INFO_KNOW_NO_AUTO("Channel Status", "CHS", ST_KNOW_channel_status_lfe | ST_KNOW_channel_status_surr_l | ST_KNOW_channel_status_surr_r | ST_KNOW_channel_status_subwoofer | ST_KNOW_channel_status_front_l | ST_KNOW_channel_status_front_r | ST_KNOW_channel_status_center, channel_status)
INFO("Lip Sync.", "LIP", 4, lip_sync)
INFO("Tuner Frequency", "TFQ", 3, tuner_frequency)
INFO("Tuner Preset", "TPR", 2, tuner_preset)
INFO("Tuner Preset Info.", "TPI", 2, tuner_preset_info)
INFO("Tuner Mode", "TMD", 2, tuner_mode)
INFO_ACK_ONLY("Tuner MEMO", "MEM")
INFO_ACK_ONLY("CLEAR", "CLR")
NO_INFO("XM Display mode", "XDP", 1) /* XXX no info on this one */
INFO_KNOW("XM Category Search", "CAT", 1, ST_KNOW_xm_in_search | ST_KNOW_xm_category, xm_category_search)
INFO("XM Category Name", "CTN", 1, xm_category_name)
INFO("XM Channel Name", "CHN", 4, xm_channel_name)
INFO("XM Artist Name", "ARN", 4, xm_artist_name)
INFO("XM Song Title", "SON", 4, xm_song_title)
NO_INFO("XM Signal Status", "SST", 1) /* XXX no info on this one */
INFO("Multi Room POWER", "MPW", 1, multiroom_power)
INFO("Multi Room AUDIO MUTE", "MAM", 1, multiroom_audio_mute)
INFO("Multi Room VOLUME", "MVL", 1, multiroom_volume)
INFO("Multi Room Volume Set", "MVS", 2, multiroom_volume_fixed)
INFO_KNOW("Multi Room SOURCE Select", "MSC", 1, ST_KNOW_multiroom_video_source | ST_KNOW_multiroom_audio_source, multiroom_source_select)
INFO("Multi Room SLEEP", "MSL", 2, multiroom_sleep)
INFO("Multi Room SPEAKER", "MSP", 2, multiroom_speaker)
INFO("Multi Room Speaker VOLUME", "MSV", 1, multiroom_speaker_volume)
INFO("Multi Room Speaker Volume Set", "MSS", 2, multiroom_speaker_volume_fixed)
INFO("Multi Room Speaker A-MUTE", "MSM", 1, multiroom_speaker_audio_mute)
INFO("Multi Room Tuner Frequency", "MTF", 3, multiroom_tuner_frequency)
INFO("Multi Room Tuner Preset", "MTP", 2, multiroom_tuner_preset)
INFO("Multi Room Tuner Mode", "MTM", 2, multiroom_tuner_mode)
INFO_CMD_ONLY("Auto status feedback", "AST", auto_status_feedback)
